

services:
  # PHP + Apache untuk Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "80:80"
    depends_on:
      - db
      - redis
    networks:
      - app-network
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: db_test
      DB_USERNAME: postgres
      DB_PASSWORD: konfirmasi
      CACHE_STORE: database
      SESSION_DRIVER: database
      QUEUE_CONNECTION: database
      REDIS_CLIENT: phpredis
      REDIS_HOST: redis
      REDIS_PORT: 6379

  # PostgreSQL sebagai Database
  db:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: konfirmasi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  # Redis sebagai Cache dan Queue
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
